--------------------------------------------------------
--  文件已创建 - 星期三-十一月-18-2020
--------------------------------------------------------
DROP TABLE "TRN_AERD_APTC";
DROP TABLE "TRN_AERD_TMRO";
DROP TABLE "TRN_AFP";
DROP TABLE "TRN_AGMT_AGREEMENT";
DROP TABLE "TRN_AGMT_AGTDTAL";
DROP TABLE "TRN_APFE";
DROP TABLE "TRN_CAPACITY";
DROP TABLE "TRN_ESMAN";
DROP TABLE "TRN_EXPD";
DROP TABLE "TRN_FTMI";
DROP TABLE "TRN_GDP";
DROP TABLE "TRN_GS";
DROP TABLE "TRN_MDRS";
DROP TABLE "TRN_MDRS_DETAIL";
DROP TABLE "TRN_MIT";
DROP TABLE "TRN_NFPD";
DROP TABLE "TRN_PADR";
DROP TABLE "TRN_PT";
DROP TABLE "TRN_TRFD";
--------------------------------------------------------
--  DDL for Table TRN_AERD_APTC
--------------------------------------------------------

  CREATE TABLE "TRN_AERD_APTC" ("AIRPORTNAMEEN" VARCHAR2(20), "STARTTIME" DATE, "ENDTIME" DATE, "UPDATETIME" DATE, "UUID" VARCHAR2(50)) ;

   COMMENT ON COLUMN "TRN_AERD_APTC"."AIRPORTNAMEEN" IS '机场四字码';
   COMMENT ON COLUMN "TRN_AERD_APTC"."STARTTIME" IS '关闭起始时间(M)';
   COMMENT ON COLUMN "TRN_AERD_APTC"."ENDTIME" IS '关闭结束时间(M)';
   COMMENT ON COLUMN "TRN_AERD_APTC"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_AERD_APTC"."UUID" IS '主键';
   COMMENT ON TABLE "TRN_AERD_APTC"  IS '机场关闭信息';
--------------------------------------------------------
--  DDL for Table TRN_AERD_TMRO
--------------------------------------------------------

  CREATE TABLE "TRN_AERD_TMRO" ("ROUTECODE" VARCHAR2(10), "STARTTIME" DATE, "ENDTIME" DATE, "UPDATETIME" DATE, "UUID" VARCHAR2(50)) ;

   COMMENT ON COLUMN "TRN_AERD_TMRO"."ROUTECODE" IS '临时航路代号';
   COMMENT ON COLUMN "TRN_AERD_TMRO"."STARTTIME" IS '开放起始时间(M)';
   COMMENT ON COLUMN "TRN_AERD_TMRO"."ENDTIME" IS '开放结束时间(M)';
   COMMENT ON COLUMN "TRN_AERD_TMRO"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_AERD_TMRO"."UUID" IS '主键';
   COMMENT ON TABLE "TRN_AERD_TMRO"  IS '临时航路开放信息';
--------------------------------------------------------
--  DDL for Table TRN_AFP
--------------------------------------------------------

  CREATE TABLE "TRN_AFP" ("RESGID" VARCHAR2(64), "RESGNAME" VARCHAR2(100), "RESCREATEUNIT" VARCHAR2(50), "RESRECVUNIT" VARCHAR2(100), "FTMIPUBLISHUNIT" VARCHAR2(20), "FTMIPUBLISHTIME" DATE, "RESREASONCODE" VARCHAR2(6), "FTMIREASON" VARCHAR2(200), "RESREASONRMK" VARCHAR2(200), "RESPARTICIPATEINCALCULATION" CHAR(1), "FTMITYPE" VARCHAR2(8), "RESSTATE" VARCHAR2(8), "FTMID" VARCHAR2(64), "RESNAME" VARCHAR2(100), "FTMISTARTTIME" DATE, "FTMIENDTIME" DATE, "RESOBJ" VARCHAR2(50), "RESRADIUS" NUMBER, "PRIORITY" CHAR(3), "FTMICONTENT" VARCHAR2(500), "VERSION" VARCHAR2(10), "UPDATETIME" DATE, "COMPANY" VARCHAR2(500)) ;

   COMMENT ON COLUMN "TRN_AFP"."RESGID" IS '流控组ID';
   COMMENT ON COLUMN "TRN_AFP"."RESGNAME" IS '流控组名称';
   COMMENT ON COLUMN "TRN_AFP"."RESCREATEUNIT" IS '流控制定单位';
   COMMENT ON COLUMN "TRN_AFP"."RESRECVUNIT" IS '流控接收单位';
   COMMENT ON COLUMN "TRN_AFP"."FTMIPUBLISHUNIT" IS '流控发布单位';
   COMMENT ON COLUMN "TRN_AFP"."FTMIPUBLISHTIME" IS '流控发布时间';
   COMMENT ON COLUMN "TRN_AFP"."RESREASONCODE" IS '流控原因代码';
   COMMENT ON COLUMN "TRN_AFP"."FTMIREASON" IS '流控原因正文';
   COMMENT ON COLUMN "TRN_AFP"."RESREASONRMK" IS '流控原因补充说明';
   COMMENT ON COLUMN "TRN_AFP"."RESPARTICIPATEINCALCULATION" IS '是否参与计算{N,Y}';
   COMMENT ON COLUMN "TRN_AFP"."FTMITYPE" IS '流控类型';
   COMMENT ON COLUMN "TRN_AFP"."RESSTATE" IS '流控状态';
   COMMENT ON COLUMN "TRN_AFP"."FTMID" IS '流控唯一标识';
   COMMENT ON COLUMN "TRN_AFP"."RESNAME" IS '流控名称';
   COMMENT ON COLUMN "TRN_AFP"."FTMISTARTTIME" IS '策略开始时间';
   COMMENT ON COLUMN "TRN_AFP"."FTMIENDTIME" IS '策略结束时间';
   COMMENT ON COLUMN "TRN_AFP"."RESOBJ" IS '策略限制对象';
   COMMENT ON COLUMN "TRN_AFP"."RESRADIUS" IS '作用半径';
   COMMENT ON COLUMN "TRN_AFP"."PRIORITY" IS '优先级';
   COMMENT ON COLUMN "TRN_AFP"."FTMICONTENT" IS '限制描述';
   COMMENT ON COLUMN "TRN_AFP"."VERSION" IS '版本号';
   COMMENT ON COLUMN "TRN_AFP"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_AFP"."COMPANY" IS '航空公司';
   COMMENT ON TABLE "TRN_AFP"  IS '3.10 流量控制信息';
--------------------------------------------------------
--  DDL for Table TRN_AGMT_AGREEMENT
--------------------------------------------------------

  CREATE TABLE "TRN_AGMT_AGREEMENT" ("AGMTID" VARCHAR2(32), "PT" VARCHAR2(20), "PTTYPE" VARCHAR2(16), "SECSRC" VARCHAR2(20), "SECDEST" VARCHAR2(20), "XFL" VARCHAR2(60), "DTALXFLTYPE" VARCHAR2(16), "SRCASPC" VARCHAR2(20), "SRCASPCTYPE" VARCHAR2(16), "DESASPC" VARCHAR2(20), "DESASPCTYPE" VARCHAR2(16), "DTALXFL" VARCHAR2(60), "UPDATETIME" DATE) ;

   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."AGMTID" IS '管制移交协议唯一ID(M)';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."PT" IS '移交点(M)';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."PTTYPE" IS '移交点类型(O)';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."SECSRC" IS '源扇区(M)';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."SECDEST" IS '目的扇区(M)';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."XFL" IS '移交高度(M)';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."DTALXFLTYPE" IS '移交高度类型';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."SRCASPC" IS '源空域单元名称';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."SRCASPCTYPE" IS '源空域单元类型';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."DESASPC" IS '目的空域单元名称';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."DESASPCTYPE" IS '目的空域单元类型';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."DTALXFL" IS '移交高度';
   COMMENT ON COLUMN "TRN_AGMT_AGREEMENT"."UPDATETIME" IS '更新时间';
   COMMENT ON TABLE "TRN_AGMT_AGREEMENT"  IS '移交协议';
--------------------------------------------------------
--  DDL for Table TRN_AGMT_AGTDTAL
--------------------------------------------------------

  CREATE TABLE "TRN_AGMT_AGTDTAL" ("SRCASPC" VARCHAR2(20), "SRCASPCTYPE" VARCHAR2(16), "DESASPC" VARCHAR2(20), "DESASPCTYPE" VARCHAR2(20), "DTALXFL" VARCHAR2(60), "DTALXFLTYPE" VARCHAR2(16), "UPDATETIME" DATE) ;

   COMMENT ON COLUMN "TRN_AGMT_AGTDTAL"."SRCASPC" IS '源空域单元名称';
   COMMENT ON COLUMN "TRN_AGMT_AGTDTAL"."SRCASPCTYPE" IS '源空域单元类型';
   COMMENT ON COLUMN "TRN_AGMT_AGTDTAL"."DESASPC" IS '目的空域单元名称';
   COMMENT ON COLUMN "TRN_AGMT_AGTDTAL"."DESASPCTYPE" IS '目的空域单元类型';
   COMMENT ON COLUMN "TRN_AGMT_AGTDTAL"."DTALXFL" IS '移交高度';
   COMMENT ON COLUMN "TRN_AGMT_AGTDTAL"."DTALXFLTYPE" IS '移交高度类型';
   COMMENT ON COLUMN "TRN_AGMT_AGTDTAL"."UPDATETIME" IS '更新时间';
   COMMENT ON TABLE "TRN_AGMT_AGTDTAL"  IS '移交细则';
--------------------------------------------------------
--  DDL for Table TRN_APFE
--------------------------------------------------------

  CREATE TABLE "TRN_APFE" ("STARTTIME" DATE, "AIRPORTNAMEEN" VARCHAR2(20), "FIX" VARCHAR2(20), "STEP" NUMBER, "ALLFLOW" NUMBER, "DEPFLOW" NUMBER, "ARRFLOW" NUMBER, "UPDATETIME" DATE) ;

   COMMENT ON COLUMN "TRN_APFE"."STARTTIME" IS '预测开始时间';
   COMMENT ON COLUMN "TRN_APFE"."AIRPORTNAMEEN" IS '机场四字码';
   COMMENT ON COLUMN "TRN_APFE"."FIX" IS '报告点';
   COMMENT ON COLUMN "TRN_APFE"."STEP" IS '预测步长';
   COMMENT ON COLUMN "TRN_APFE"."ALLFLOW" IS '总量';
   COMMENT ON COLUMN "TRN_APFE"."DEPFLOW" IS '起飞/离场流量';
   COMMENT ON COLUMN "TRN_APFE"."ARRFLOW" IS '降落/进场流量';
   COMMENT ON COLUMN "TRN_APFE"."UPDATETIME" IS '更新时间';
   COMMENT ON TABLE "TRN_APFE"  IS '3.9 机场流量预测信息';
--------------------------------------------------------
--  DDL for Table TRN_CAPACITY
--------------------------------------------------------

  CREATE TABLE "TRN_CAPACITY" ("TEFF" DATE, "TEXP" DATE, "TISSUE" DATE, "DSTYPE" CHAR(1), "STEP" NUMBER, "AIRSPACETYPE" VARCHAR2(16), "AREA" VARCHAR2(20), "AIRPORTNAMEEN" VARCHAR2(20), "AIRPORT_CAPVALUE" NUMBER, "ADR" NUMBER, "AAR" NUMBER, "AIRPORT_FACTOR" VARCHAR2(16), "SECTID" NUMBER, "NAME" VARCHAR2(20), "SECTOR_CAPVALUE" NUMBER, "SECTOR_FACTOR" VARCHAR2(16), "TERM_NAME" VARCHAR2(20), "TERM_CAPVALUE" NUMBER, "TERM_ADR" NUMBER, "TERM_AAR" NUMBER, "FIX_NAME" VARCHAR2(20), "FIX_TYPE" CHAR(1), "FIX_CAPVALUE" NUMBER, "UPDATETIME" DATE) ;

   COMMENT ON COLUMN "TRN_CAPACITY"."TEFF" IS '开始时间';
   COMMENT ON COLUMN "TRN_CAPACITY"."TEXP" IS '结束时间';
   COMMENT ON COLUMN "TRN_CAPACITY"."TISSUE" IS '审核时间';
   COMMENT ON COLUMN "TRN_CAPACITY"."DSTYPE" IS '审批类型';
   COMMENT ON COLUMN "TRN_CAPACITY"."STEP" IS '时间粒度';
   COMMENT ON COLUMN "TRN_CAPACITY"."AIRSPACETYPE" IS '空域对象类型';
   COMMENT ON COLUMN "TRN_CAPACITY"."AREA" IS '地区';
   COMMENT ON COLUMN "TRN_CAPACITY"."AIRPORTNAMEEN" IS '机场名称';
   COMMENT ON COLUMN "TRN_CAPACITY"."AIRPORT_CAPVALUE" IS '容量值';
   COMMENT ON COLUMN "TRN_CAPACITY"."ADR" IS '离港容量值';
   COMMENT ON COLUMN "TRN_CAPACITY"."AAR" IS '进港容量值';
   COMMENT ON COLUMN "TRN_CAPACITY"."AIRPORT_FACTOR" IS '条件';
   COMMENT ON COLUMN "TRN_CAPACITY"."SECTID" IS '扇区ID';
   COMMENT ON COLUMN "TRN_CAPACITY"."NAME" IS '扇区名称';
   COMMENT ON COLUMN "TRN_CAPACITY"."SECTOR_CAPVALUE" IS '容量值';
   COMMENT ON COLUMN "TRN_CAPACITY"."SECTOR_FACTOR" IS '条件';
   COMMENT ON COLUMN "TRN_CAPACITY"."TERM_NAME" IS '终端区名称';
   COMMENT ON COLUMN "TRN_CAPACITY"."TERM_CAPVALUE" IS '容量值';
   COMMENT ON COLUMN "TRN_CAPACITY"."TERM_ADR" IS '离港容量值';
   COMMENT ON COLUMN "TRN_CAPACITY"."TERM_AAR" IS '进港容量值';
   COMMENT ON COLUMN "TRN_CAPACITY"."FIX_NAME" IS '监视点名称';
   COMMENT ON COLUMN "TRN_CAPACITY"."FIX_TYPE" IS '监视点类型';
   COMMENT ON COLUMN "TRN_CAPACITY"."FIX_CAPVALUE" IS '监视点容量';
   COMMENT ON COLUMN "TRN_CAPACITY"."UPDATETIME" IS '修改时间';
   COMMENT ON TABLE "TRN_CAPACITY"  IS '容量信息';
--------------------------------------------------------
--  DDL for Table TRN_ESMAN
--------------------------------------------------------

  CREATE TABLE "TRN_ESMAN" ("ARCID" VARCHAR2(10), "ADEP" VARCHAR2(20), "ADES" VARCHAR2(20), "STOT" DATE, "ETD" DATE, "ATOT" DATE, "PTID" VARCHAR2(50), "PTCTO" DATE, "PTFL" VARCHAR2(6), "UPDATETIME" DATE, "IDENTIFIER" VARCHAR2(64)) ;

   COMMENT ON COLUMN "TRN_ESMAN"."ARCID" IS '航空器识别标志';
   COMMENT ON COLUMN "TRN_ESMAN"."ADEP" IS '起飞机场';
   COMMENT ON COLUMN "TRN_ESMAN"."ADES" IS '目的地机场';
   COMMENT ON COLUMN "TRN_ESMAN"."STOT" IS '计划起飞时间';
   COMMENT ON COLUMN "TRN_ESMAN"."ETD" IS '变更起飞时间';
   COMMENT ON COLUMN "TRN_ESMAN"."ATOT" IS '实际起飞时间';
   COMMENT ON COLUMN "TRN_ESMAN"."PTID" IS '航路点名(排序点)';
   COMMENT ON COLUMN "TRN_ESMAN"."PTCTO" IS '建议过排序点时间';
   COMMENT ON COLUMN "TRN_ESMAN"."PTFL" IS '建议过排序点高度';
   COMMENT ON COLUMN "TRN_ESMAN"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_ESMAN"."IDENTIFIER" IS '主键';
   COMMENT ON TABLE "TRN_ESMAN"  IS '计算过受控区信息';
--------------------------------------------------------
--  DDL for Table TRN_EXPD
--------------------------------------------------------

  CREATE TABLE "TRN_EXPD" ("FTMID" VARCHAR2(50), "CONTAINFLAG" CHAR(1), "ADEP" VARCHAR2(100), "ADES" VARCHAR2(100), "COMEROUTE" VARCHAR2(100), "DESTROUTE" VARCHAR2(100), "COMECTA" VARCHAR2(100), "DESTCTA" VARCHAR2(100), "COMEFIX" VARCHAR2(100), "DESTFIX" VARCHAR2(100), "FLYDIR" VARCHAR2(100), "ARCID" VARCHAR2(100), "TURB" VARCHAR2(10), "FLIGHTNATURE" VARCHAR2(10), "OPERATOR" VARCHAR2(10), "ARMYCIVIL" VARCHAR2(5), "PASSENGERCARGO" VARCHAR2(5), "FLYTYPE" VARCHAR2(100), "TASK" VARCHAR2(100), "ARCTYPE" VARCHAR2(100), "AIRLINE" VARCHAR2(100), "FLYDIS" VARCHAR2(100), "RVSM" VARCHAR2(5), "RNP" VARCHAR2(5), "RNAV" VARCHAR2(50), "CAT" VARCHAR2(50), "RFLTYPE" CHAR(1), "RFL" VARCHAR2(50), "UPDATETIME" DATE) ;

   COMMENT ON COLUMN "TRN_EXPD"."FTMID" IS '流控唯一标识';
   COMMENT ON COLUMN "TRN_EXPD"."CONTAINFLAG" IS '包含关系';
   COMMENT ON COLUMN "TRN_EXPD"."ADEP" IS '起飞机场';
   COMMENT ON COLUMN "TRN_EXPD"."ADES" IS '降落机场';
   COMMENT ON COLUMN "TRN_EXPD"."COMEROUTE" IS '航路（来向）';
   COMMENT ON COLUMN "TRN_EXPD"."DESTROUTE" IS '航路（去向）';
   COMMENT ON COLUMN "TRN_EXPD"."COMECTA" IS '管制区（来向）';
   COMMENT ON COLUMN "TRN_EXPD"."DESTCTA" IS '管制区（去向）';
   COMMENT ON COLUMN "TRN_EXPD"."COMEFIX" IS '航路点（来向）';
   COMMENT ON COLUMN "TRN_EXPD"."DESTFIX" IS '航路点（去向）';
   COMMENT ON COLUMN "TRN_EXPD"."FLYDIR" IS '飞行方向';
   COMMENT ON COLUMN "TRN_EXPD"."ARCID" IS '航班号';
   COMMENT ON COLUMN "TRN_EXPD"."TURB" IS '尾流';
   COMMENT ON COLUMN "TRN_EXPD"."FLIGHTNATURE" IS '航班性质';
   COMMENT ON COLUMN "TRN_EXPD"."OPERATOR" IS '运营人';
   COMMENT ON COLUMN "TRN_EXPD"."ARMYCIVIL" IS '军民航';
   COMMENT ON COLUMN "TRN_EXPD"."PASSENGERCARGO" IS '客货';
   COMMENT ON COLUMN "TRN_EXPD"."FLYTYPE" IS '飞行类型';
   COMMENT ON COLUMN "TRN_EXPD"."TASK" IS '任务性质';
   COMMENT ON COLUMN "TRN_EXPD"."ARCTYPE" IS '机型';
   COMMENT ON COLUMN "TRN_EXPD"."AIRLINE" IS '航空公司';
   COMMENT ON COLUMN "TRN_EXPD"."FLYDIS" IS '飞行时长';
   COMMENT ON COLUMN "TRN_EXPD"."RVSM" IS 'RVSM能力';
   COMMENT ON COLUMN "TRN_EXPD"."RNP" IS 'RNP能力';
   COMMENT ON COLUMN "TRN_EXPD"."RNAV" IS 'RNAV能力';
   COMMENT ON COLUMN "TRN_EXPD"."CAT" IS 'CAT能力';
   COMMENT ON COLUMN "TRN_EXPD"."RFLTYPE" IS '高度类型';
   COMMENT ON COLUMN "TRN_EXPD"."RFL" IS '巡航高度';
   COMMENT ON COLUMN "TRN_EXPD"."UPDATETIME" IS '更新时间';
--------------------------------------------------------
--  DDL for Table TRN_FTMI
--------------------------------------------------------

  CREATE TABLE "TRN_FTMI" ("FTMID" VARCHAR2(64), "FTMIPUBLISHTIME" DATE, "FTMIPUBLISHUNIT" VARCHAR2(20), "FTMISTARTTIME" DATE, "FTMIENDTIME" DATE, "FTMITYPE" VARCHAR2(16), "FTMICONTENT" VARCHAR2(500), "FTMIREASON" VARCHAR2(500), "MDRSIDENTIFICATION" VARCHAR2(32), "UPDATETIME" DATE, "COMPANY" VARCHAR2(500)) ;

   COMMENT ON COLUMN "TRN_FTMI"."FTMID" IS '流控标识';
   COMMENT ON COLUMN "TRN_FTMI"."FTMIPUBLISHTIME" IS '流控发布时间';
   COMMENT ON COLUMN "TRN_FTMI"."FTMIPUBLISHUNIT" IS '流控发布单位';
   COMMENT ON COLUMN "TRN_FTMI"."FTMISTARTTIME" IS '流控开始时间';
   COMMENT ON COLUMN "TRN_FTMI"."FTMIENDTIME" IS '流控结束时间';
   COMMENT ON COLUMN "TRN_FTMI"."FTMITYPE" IS '流控类型';
   COMMENT ON COLUMN "TRN_FTMI"."FTMICONTENT" IS '流控主要内容';
   COMMENT ON COLUMN "TRN_FTMI"."FTMIREASON" IS '流控限制原因';
   COMMENT ON COLUMN "TRN_FTMI"."MDRSIDENTIFICATION" IS 'MDRS标识';
   COMMENT ON COLUMN "TRN_FTMI"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_FTMI"."COMPANY" IS '航空公司';
   COMMENT ON TABLE "TRN_FTMI"  IS '流量控制措施';
--------------------------------------------------------
--  DDL for Table TRN_GDP
--------------------------------------------------------

  CREATE TABLE "TRN_GDP" ("RESGID" VARCHAR2(64), "RESGNAME" VARCHAR2(100), "RESCREATEUNIT" VARCHAR2(50), "RESRECVUNIT" VARCHAR2(100), "FTMIPUBLISHUNIT" VARCHAR2(20), "FTMIPUBLISHTIME" DATE, "RESREASONCODE" VARCHAR2(6), "FTMIREASON" VARCHAR2(200), "RESREASONRMK" VARCHAR2(200), "RESPARTICIPATEINCALCULATION" CHAR(1), "FTMITYPE" VARCHAR2(8), "RESSTATE" VARCHAR2(8), "FTMID" VARCHAR2(64), "RESNAME" VARCHAR2(100), "FTMISTARTTIME" DATE, "FTMIENDTIME" DATE, "RESOBJ" VARCHAR2(50), "RESRADIUS" NUMBER, "PRIORITY" CHAR(3), "FTMICONTENT" VARCHAR2(500), "VERSION" VARCHAR2(10), "UPDATETIME" DATE, "COMPANY" VARCHAR2(500)) ;

   COMMENT ON COLUMN "TRN_GDP"."RESGID" IS '流控组ID';
   COMMENT ON COLUMN "TRN_GDP"."RESGNAME" IS '流控组名称';
   COMMENT ON COLUMN "TRN_GDP"."RESCREATEUNIT" IS '流控制定单位';
   COMMENT ON COLUMN "TRN_GDP"."RESRECVUNIT" IS '流控接收单位';
   COMMENT ON COLUMN "TRN_GDP"."FTMIPUBLISHUNIT" IS '流控发布单位';
   COMMENT ON COLUMN "TRN_GDP"."FTMIPUBLISHTIME" IS '流控发布时间';
   COMMENT ON COLUMN "TRN_GDP"."RESREASONCODE" IS '流控原因代码';
   COMMENT ON COLUMN "TRN_GDP"."FTMIREASON" IS '流控原因正文';
   COMMENT ON COLUMN "TRN_GDP"."RESREASONRMK" IS '流控原因补充说明';
   COMMENT ON COLUMN "TRN_GDP"."RESPARTICIPATEINCALCULATION" IS '是否参与计算{N,Y}';
   COMMENT ON COLUMN "TRN_GDP"."FTMITYPE" IS '流控类型';
   COMMENT ON COLUMN "TRN_GDP"."RESSTATE" IS '流控状态';
   COMMENT ON COLUMN "TRN_GDP"."FTMID" IS '流控唯一标识';
   COMMENT ON COLUMN "TRN_GDP"."RESNAME" IS '流控名称';
   COMMENT ON COLUMN "TRN_GDP"."FTMISTARTTIME" IS '策略开始时间';
   COMMENT ON COLUMN "TRN_GDP"."FTMIENDTIME" IS '策略结束时间';
   COMMENT ON COLUMN "TRN_GDP"."RESOBJ" IS '策略限制对象';
   COMMENT ON COLUMN "TRN_GDP"."RESRADIUS" IS '作用半径';
   COMMENT ON COLUMN "TRN_GDP"."PRIORITY" IS '优先级';
   COMMENT ON COLUMN "TRN_GDP"."FTMICONTENT" IS '限制描述';
   COMMENT ON COLUMN "TRN_GDP"."VERSION" IS '版本号';
   COMMENT ON COLUMN "TRN_GDP"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_GDP"."COMPANY" IS '航空公司';
   COMMENT ON TABLE "TRN_GDP"  IS '3.10 流量控制信息';
--------------------------------------------------------
--  DDL for Table TRN_GS
--------------------------------------------------------

  CREATE TABLE "TRN_GS" ("RESGID" VARCHAR2(64), "RESGNAME" VARCHAR2(100), "RESCREATEUNIT" VARCHAR2(50), "RESRECVUNIT" VARCHAR2(100), "FTMIPUBLISHUNIT" VARCHAR2(20), "FTMIPUBLISHTIME" DATE, "RESREASONCODE" VARCHAR2(6), "FTMIREASON" VARCHAR2(200), "RESREASONRMK" VARCHAR2(200), "RESPARTICIPATEINCALCULATION" CHAR(1), "FTMITYPE" VARCHAR2(8), "RESSTATE" VARCHAR2(8), "FTMID" VARCHAR2(64), "RESNAME" VARCHAR2(100), "FTMISTARTTIME" DATE, "FTMIENDTIME" DATE, "RESOBJ" VARCHAR2(50), "PRIORITY" CHAR(3), "FTMICONTENT" VARCHAR2(500), "VERSION" VARCHAR2(10), "UPDATETIME" DATE, "COMPANY" VARCHAR2(500)) ;

   COMMENT ON COLUMN "TRN_GS"."RESGID" IS '流控组ID';
   COMMENT ON COLUMN "TRN_GS"."RESGNAME" IS '流控组名称';
   COMMENT ON COLUMN "TRN_GS"."RESCREATEUNIT" IS '流控制定单位';
   COMMENT ON COLUMN "TRN_GS"."RESRECVUNIT" IS '流控接收单位';
   COMMENT ON COLUMN "TRN_GS"."FTMIPUBLISHUNIT" IS '流控发布单位';
   COMMENT ON COLUMN "TRN_GS"."FTMIPUBLISHTIME" IS '流控发布时间';
   COMMENT ON COLUMN "TRN_GS"."RESREASONCODE" IS '流控原因代码';
   COMMENT ON COLUMN "TRN_GS"."FTMIREASON" IS '流控原因正文';
   COMMENT ON COLUMN "TRN_GS"."RESREASONRMK" IS '流控原因补充说明';
   COMMENT ON COLUMN "TRN_GS"."RESPARTICIPATEINCALCULATION" IS '是否参与计算{N,Y}';
   COMMENT ON COLUMN "TRN_GS"."FTMITYPE" IS '流控类型';
   COMMENT ON COLUMN "TRN_GS"."RESSTATE" IS '流控状态';
   COMMENT ON COLUMN "TRN_GS"."FTMID" IS '流控唯一标识';
   COMMENT ON COLUMN "TRN_GS"."RESNAME" IS '流控名称';
   COMMENT ON COLUMN "TRN_GS"."FTMISTARTTIME" IS '策略开始时间';
   COMMENT ON COLUMN "TRN_GS"."FTMIENDTIME" IS '策略结束时间';
   COMMENT ON COLUMN "TRN_GS"."RESOBJ" IS '策略限制对象';
   COMMENT ON COLUMN "TRN_GS"."PRIORITY" IS '优先级';
   COMMENT ON COLUMN "TRN_GS"."FTMICONTENT" IS '限制描述';
   COMMENT ON COLUMN "TRN_GS"."VERSION" IS '版本号';
   COMMENT ON COLUMN "TRN_GS"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_GS"."COMPANY" IS '航空公司';
   COMMENT ON TABLE "TRN_GS"  IS '3.10 流量控制信息';
--------------------------------------------------------
--  DDL for Table TRN_MDRS
--------------------------------------------------------

  CREATE TABLE "TRN_MDRS" ("MDRSNAME" VARCHAR2(100), "MDRSPUBLISHTIME" DATE, "MDRSPUBLISHUNIT" VARCHAR2(100), "MDRSAREA" VARCHAR2(100), "MDRSREASON" VARCHAR2(600), "MDRSEXPECTRESPOND" VARCHAR2(3000), "UPDATETIME" DATE, "MDRSID" VARCHAR2(32), "MDRSREASONCODE" VARCHAR2(6) DEFAULT 000000, "VERSION" VARCHAR2(10) DEFAULT 1.0) ;

   COMMENT ON COLUMN "TRN_MDRS"."MDRSNAME" IS 'MDRS通告名称';
   COMMENT ON COLUMN "TRN_MDRS"."MDRSPUBLISHTIME" IS 'MDRS发布时间';
   COMMENT ON COLUMN "TRN_MDRS"."MDRSPUBLISHUNIT" IS 'MDRS发布单位';
   COMMENT ON COLUMN "TRN_MDRS"."MDRSAREA" IS 'MDRS区域描述';
   COMMENT ON COLUMN "TRN_MDRS"."MDRSREASON" IS 'MDRS发布原因';
   COMMENT ON COLUMN "TRN_MDRS"."MDRSEXPECTRESPOND" IS 'MDRS预期响应信息';
   COMMENT ON COLUMN "TRN_MDRS"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_MDRS"."MDRSID" IS 'MDRSID';
   COMMENT ON COLUMN "TRN_MDRS"."MDRSREASONCODE" IS 'MDRS发布原因代码';
   COMMENT ON COLUMN "TRN_MDRS"."VERSION" IS '版本号';
   COMMENT ON TABLE "TRN_MDRS"  IS 'MDRS信息';
--------------------------------------------------------
--  DDL for Table TRN_MDRS_DETAIL
--------------------------------------------------------

  CREATE TABLE "TRN_MDRS_DETAIL" ("ID" VARCHAR2(32), "MDRS_ID" VARCHAR2(32), "MDRS_LEVEL" VARCHAR2(4), "EXPECT_INFLUENCE" VARCHAR2(3000), "SCOPE_BEG_TIME" DATE, "SCOPE_END_TIME" DATE, "UPDATETIME" DATE) ;

   COMMENT ON COLUMN "TRN_MDRS_DETAIL"."ID" IS 'MDRS各时段预期影响主键';
   COMMENT ON COLUMN "TRN_MDRS_DETAIL"."MDRS_ID" IS 'MDRS主键';
   COMMENT ON COLUMN "TRN_MDRS_DETAIL"."MDRS_LEVEL" IS 'MDRS预警等级';
   COMMENT ON COLUMN "TRN_MDRS_DETAIL"."EXPECT_INFLUENCE" IS 'MDRS预期影响描述';
   COMMENT ON COLUMN "TRN_MDRS_DETAIL"."SCOPE_BEG_TIME" IS 'MDRS作用开始时间';
   COMMENT ON COLUMN "TRN_MDRS_DETAIL"."SCOPE_END_TIME" IS 'MDRS作用截止时间';
   COMMENT ON COLUMN "TRN_MDRS_DETAIL"."UPDATETIME" IS '更新时间';
--------------------------------------------------------
--  DDL for Table TRN_MIT
--------------------------------------------------------

  CREATE TABLE "TRN_MIT" ("RESGID" VARCHAR2(64), "RESGNAME" VARCHAR2(100), "RESCREATEUNIT" VARCHAR2(50), "RESRECVUNIT" VARCHAR2(100), "FTMIPUBLISHUNIT" VARCHAR2(20), "FTMIPUBLISHTIME" DATE, "RESREASONCODE" VARCHAR2(6), "FTMIREASON" VARCHAR2(200), "RESREASONRMK" VARCHAR2(200), "RESPARTICIPATEINCALCULATION" CHAR(1), "FTMITYPE" VARCHAR2(8), "RESSTATE" VARCHAR2(8), "FTMID" VARCHAR2(50), "RESNAME" VARCHAR2(100), "FTMISTARTTIME" DATE, "FTMIENDTIME" DATE, "RESOBJ" VARCHAR2(50), "CALC_MODE" CHAR(1), "MITTYPE" CHAR(1), "VOLUMEPIECE" NUMBER, "VOLUMENUM" NUMBER, "INTVTYPE" CHAR(1), "INTVVALUE" NUMBER, "MININTVTYPE" CHAR(1), "MININTVVALUE" NUMBER, "SAMEALT" CHAR(1), "RESALTTYPE" CHAR(1), "RESALTVALUE" VARCHAR2(200), "RESSPECIAL" CHAR(1), "RESATTR" CHAR(1), "PRIORITY" CHAR(3), "FTMICONTENT" VARCHAR2(500), "UPDATETIME" DATE, "COMPANY" VARCHAR2(500)) ;

   COMMENT ON COLUMN "TRN_MIT"."RESGID" IS '流控组ID';
   COMMENT ON COLUMN "TRN_MIT"."RESGNAME" IS '流控组名称';
   COMMENT ON COLUMN "TRN_MIT"."RESCREATEUNIT" IS '流控制定单位';
   COMMENT ON COLUMN "TRN_MIT"."RESRECVUNIT" IS '流控接收单位';
   COMMENT ON COLUMN "TRN_MIT"."FTMIPUBLISHUNIT" IS '流控发布单位';
   COMMENT ON COLUMN "TRN_MIT"."FTMIPUBLISHTIME" IS '流控发布时间';
   COMMENT ON COLUMN "TRN_MIT"."RESREASONCODE" IS '流控原因代码';
   COMMENT ON COLUMN "TRN_MIT"."FTMIREASON" IS '流控原因正文';
   COMMENT ON COLUMN "TRN_MIT"."RESREASONRMK" IS '流控原因补充说明';
   COMMENT ON COLUMN "TRN_MIT"."RESPARTICIPATEINCALCULATION" IS '是否参与计算{N,Y}';
   COMMENT ON COLUMN "TRN_MIT"."FTMITYPE" IS '流控类型';
   COMMENT ON COLUMN "TRN_MIT"."RESSTATE" IS '流控状态';
   COMMENT ON COLUMN "TRN_MIT"."FTMID" IS '流控唯一标识';
   COMMENT ON COLUMN "TRN_MIT"."RESNAME" IS '流控名称';
   COMMENT ON COLUMN "TRN_MIT"."FTMISTARTTIME" IS '策略开始时间';
   COMMENT ON COLUMN "TRN_MIT"."FTMIENDTIME" IS '策略结束时间';
   COMMENT ON COLUMN "TRN_MIT"."RESOBJ" IS '策略限制对象';
   COMMENT ON COLUMN "TRN_MIT"."CALC_MODE" IS '计算模式';
   COMMENT ON COLUMN "TRN_MIT"."MITTYPE" IS '间隔限制类型';
   COMMENT ON COLUMN "TRN_MIT"."VOLUMEPIECE" IS '总量时间片';
   COMMENT ON COLUMN "TRN_MIT"."VOLUMENUM" IS '单位时间片总量架次';
   COMMENT ON COLUMN "TRN_MIT"."INTVTYPE" IS '间隔类型';
   COMMENT ON COLUMN "TRN_MIT"."INTVVALUE" IS '间隔值';
   COMMENT ON COLUMN "TRN_MIT"."MININTVTYPE" IS '最小间隔类型';
   COMMENT ON COLUMN "TRN_MIT"."MININTVVALUE" IS '最小间隔值';
   COMMENT ON COLUMN "TRN_MIT"."SAMEALT" IS '是否为同高度限制';
   COMMENT ON COLUMN "TRN_MIT"."RESALTTYPE" IS '高度限制类型';
   COMMENT ON COLUMN "TRN_MIT"."RESALTVALUE" IS '限制高度值';
   COMMENT ON COLUMN "TRN_MIT"."RESSPECIAL" IS '特殊限制';
   COMMENT ON COLUMN "TRN_MIT"."RESATTR" IS '限制属性';
   COMMENT ON COLUMN "TRN_MIT"."PRIORITY" IS '优先级';
   COMMENT ON COLUMN "TRN_MIT"."FTMICONTENT" IS '限制描述';
   COMMENT ON COLUMN "TRN_MIT"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_MIT"."COMPANY" IS '航空公司';
   COMMENT ON TABLE "TRN_MIT"  IS '3.10 流量控制信息';
--------------------------------------------------------
--  DDL for Table TRN_NFPD
--------------------------------------------------------

  CREATE TABLE "TRN_NFPD" ("ARCID" VARCHAR2(10), "GUFI" VARCHAR2(32), "GUID" VARCHAR2(32), "REGID" VARCHAR2(10), "ADEP" VARCHAR2(10), "ADES" VARCHAR2(10), "ARCADDR" VARCHAR2(6), "ASSR" VARCHAR2(5), "ARCTYPE" VARCHAR2(10), "TURB" VARCHAR2(1), "VIP" VARCHAR2(10), "PTYPE" VARCHAR2(3), "FLYTYPE" VARCHAR2(100), "SOBT" DATE, "SDEPAP" VARCHAR2(20), "SARRAP" VARCHAR2(20), "EOBT" DATE, "ELDT" DATE, "FPDSTAT" VARCHAR2(3), "FARCID" VARCHAR2(10), "FCTOT" DATE, "FSTAT" VARCHAR2(3), "CTOT" DATE, "COBT" DATE, "CLDT" DATE, "FTMID" VARCHAR2(1000), "FTMIEXMPT" VARCHAR2(1000), "FTMICONTENT" CLOB, "RESFLAG" VARCHAR2(1), "WAITSOURCE" VARCHAR2(1), "PROTECT" VARCHAR2(1), "UPDATETIME" DATE, "COMPANY" VARCHAR2(3), "EXECDATE" DATE, "MISSIONPROPERTY" VARCHAR2(4), "CNRSSTATUS" VARCHAR2(1), "ROUTE" VARCHAR2(1000), "ATOT" DATE, "FLIGHTLOCK" NUMBER(1,0)) ;

   COMMENT ON COLUMN "TRN_NFPD"."ARCID" IS '航空器识别标志';
   COMMENT ON COLUMN "TRN_NFPD"."GUFI" IS '全球航班唯一标识符';
   COMMENT ON COLUMN "TRN_NFPD"."GUID" IS '航班唯一标识符';
   COMMENT ON COLUMN "TRN_NFPD"."REGID" IS '航空器注册号';
   COMMENT ON COLUMN "TRN_NFPD"."ADEP" IS '起飞机场';
   COMMENT ON COLUMN "TRN_NFPD"."ADES" IS '目的地机场';
   COMMENT ON COLUMN "TRN_NFPD"."ARCADDR" IS '航空器地址码';
   COMMENT ON COLUMN "TRN_NFPD"."ASSR" IS '二次代码';
   COMMENT ON COLUMN "TRN_NFPD"."ARCTYPE" IS '机型';
   COMMENT ON COLUMN "TRN_NFPD"."TURB" IS '尾流';
   COMMENT ON COLUMN "TRN_NFPD"."VIP" IS '要客信息';
   COMMENT ON COLUMN "TRN_NFPD"."PTYPE" IS '航班类型';
   COMMENT ON COLUMN "TRN_NFPD"."FLYTYPE" IS '飞行类型';
   COMMENT ON COLUMN "TRN_NFPD"."SOBT" IS '计划离港时间';
   COMMENT ON COLUMN "TRN_NFPD"."SDEPAP" IS '计划起飞机场';
   COMMENT ON COLUMN "TRN_NFPD"."SARRAP" IS '计划目的地机场';
   COMMENT ON COLUMN "TRN_NFPD"."EOBT" IS '预计撤轮挡时间';
   COMMENT ON COLUMN "TRN_NFPD"."ELDT" IS '预计降落时间';
   COMMENT ON COLUMN "TRN_NFPD"."FPDSTAT" IS '当前航班状态';
   COMMENT ON COLUMN "TRN_NFPD"."FARCID" IS '前序航班的航班号';
   COMMENT ON COLUMN "TRN_NFPD"."FCTOT" IS '前序航班计算起飞时间';
   COMMENT ON COLUMN "TRN_NFPD"."FSTAT" IS '前序航班状态';
   COMMENT ON COLUMN "TRN_NFPD"."CTOT" IS '计算起飞时间';
   COMMENT ON COLUMN "TRN_NFPD"."COBT" IS '计算撤轮挡时间';
   COMMENT ON COLUMN "TRN_NFPD"."CLDT" IS '计算降落时间';
   COMMENT ON COLUMN "TRN_NFPD"."FTMID" IS '流控标识';
   COMMENT ON COLUMN "TRN_NFPD"."FTMIEXMPT" IS '航班豁免流控标识';
   COMMENT ON COLUMN "TRN_NFPD"."FTMICONTENT" IS '流控内容';
   COMMENT ON COLUMN "TRN_NFPD"."RESFLAG" IS '航班受控标识';
   COMMENT ON COLUMN "TRN_NFPD"."WAITSOURCE" IS '等待池标识';
   COMMENT ON COLUMN "TRN_NFPD"."PROTECT" IS '保护池标识';
   COMMENT ON COLUMN "TRN_NFPD"."UPDATETIME" IS '更新时间';
   COMMENT ON COLUMN "TRN_NFPD"."COMPANY" IS '航空公司';
   COMMENT ON COLUMN "TRN_NFPD"."EXECDATE" IS '执行日期';
   COMMENT ON COLUMN "TRN_NFPD"."MISSIONPROPERTY" IS '任务属性';
   COMMENT ON COLUMN "TRN_NFPD"."CNRSSTATUS" IS '航班取消标记';
   COMMENT ON COLUMN "TRN_NFPD"."ROUTE" IS '航路信息';
   COMMENT ON COLUMN "TRN_NFPD"."ATOT" IS '实际起飞时间';
   COMMENT ON COLUMN "TRN_NFPD"."FLIGHTLOCK" IS '锁定标记';
   COMMENT ON TABLE "TRN_NFPD"  IS '全国航班动态';
--------------------------------------------------------
--  DDL for Table TRN_PADR
--------------------------------------------------------

  CREATE TABLE "TRN_PADR" ("AIRPORTNAMEEN" VARCHAR2(128), "STARTTIME" DATE, "STEP" NUMBER, "CAPACITY" NUMBER, "UPDATETIME" DATE) ;

   COMMENT ON COLUMN "TRN_PADR"."AIRPORTNAMEEN" IS '机场四字码';
   COMMENT ON COLUMN "TRN_PADR"."STARTTIME" IS '开始时间';
   COMMENT ON COLUMN "TRN_PADR"."STEP" IS '时间粒度';
   COMMENT ON COLUMN "TRN_PADR"."CAPACITY" IS '机场容量';
   COMMENT ON COLUMN "TRN_PADR"."UPDATETIME" IS '更新时间';
--------------------------------------------------------
--  DDL for Table TRN_PT
--------------------------------------------------------

  CREATE TABLE "TRN_PT" ("PTID" VARCHAR2(50), "PTCTO" DATE, "PTFL" VARCHAR2(6), "UPDATETIME" DATE) ;

   COMMENT ON COLUMN "TRN_PT"."PTID" IS '航路点名(排序点)';
   COMMENT ON COLUMN "TRN_PT"."PTCTO" IS '建议过排序点时间';
   COMMENT ON COLUMN "TRN_PT"."PTFL" IS '建议过排序点高度';
   COMMENT ON COLUMN "TRN_PT"."UPDATETIME" IS '更新时间';
--------------------------------------------------------
--  DDL for Table TRN_TRFD
--------------------------------------------------------

  CREATE TABLE "TRN_TRFD" ("FTMID" VARCHAR2(50), "CONTAINFLAG" CHAR(1), "ADEP" VARCHAR2(100), "ADES" VARCHAR2(100), "COMEROUTE" VARCHAR2(100), "DESTROUTE" VARCHAR2(100), "COMECTA" VARCHAR2(100), "DESTCTA" VARCHAR2(100), "COMEFIX" VARCHAR2(100), "DESTFIX" VARCHAR2(100), "FLYDIR" VARCHAR2(100), "ARCID" VARCHAR2(100), "TURB" VARCHAR2(10), "FLIGHTNATURE" VARCHAR2(10), "OPERATOR" VARCHAR2(10), "ARMYCIVIL" VARCHAR2(5), "PASSENGERCARGO" VARCHAR2(5), "FLYTYPE" VARCHAR2(100), "TASK" VARCHAR2(100), "ARCTYPE" VARCHAR2(100), "AIRLINE" VARCHAR2(100), "FLYDIS" VARCHAR2(100), "RVSM" VARCHAR2(5), "RNP" VARCHAR2(5), "RNAV" VARCHAR2(50), "CAT" VARCHAR2(50), "RFLTYPE" CHAR(1), "RFL" VARCHAR2(50), "UPDATETIME" DATE) ;

   COMMENT ON COLUMN "TRN_TRFD"."FTMID" IS '流控唯一标识';
   COMMENT ON COLUMN "TRN_TRFD"."CONTAINFLAG" IS '包含关系';
   COMMENT ON COLUMN "TRN_TRFD"."ADEP" IS '起飞机场';
   COMMENT ON COLUMN "TRN_TRFD"."ADES" IS '降落机场';
   COMMENT ON COLUMN "TRN_TRFD"."COMEROUTE" IS '航路（来向）';
   COMMENT ON COLUMN "TRN_TRFD"."DESTROUTE" IS '航路（去向）';
   COMMENT ON COLUMN "TRN_TRFD"."COMECTA" IS '管制区（来向）';
   COMMENT ON COLUMN "TRN_TRFD"."DESTCTA" IS '管制区（去向）';
   COMMENT ON COLUMN "TRN_TRFD"."COMEFIX" IS '航路点（来向）';
   COMMENT ON COLUMN "TRN_TRFD"."DESTFIX" IS '航路点（去向）';
   COMMENT ON COLUMN "TRN_TRFD"."FLYDIR" IS '飞行方向';
   COMMENT ON COLUMN "TRN_TRFD"."ARCID" IS '航班号';
   COMMENT ON COLUMN "TRN_TRFD"."TURB" IS '尾流';
   COMMENT ON COLUMN "TRN_TRFD"."FLIGHTNATURE" IS '航班性质';
   COMMENT ON COLUMN "TRN_TRFD"."OPERATOR" IS '运营人';
   COMMENT ON COLUMN "TRN_TRFD"."ARMYCIVIL" IS '军民航';
   COMMENT ON COLUMN "TRN_TRFD"."PASSENGERCARGO" IS '客货';
   COMMENT ON COLUMN "TRN_TRFD"."FLYTYPE" IS '飞行类型';
   COMMENT ON COLUMN "TRN_TRFD"."TASK" IS '任务性质';
   COMMENT ON COLUMN "TRN_TRFD"."ARCTYPE" IS '机型';
   COMMENT ON COLUMN "TRN_TRFD"."AIRLINE" IS '航空公司';
   COMMENT ON COLUMN "TRN_TRFD"."FLYDIS" IS '飞行时长';
   COMMENT ON COLUMN "TRN_TRFD"."RVSM" IS 'RVSM能力';
   COMMENT ON COLUMN "TRN_TRFD"."RNP" IS 'RNP能力';
   COMMENT ON COLUMN "TRN_TRFD"."RNAV" IS 'RNAV能力';
   COMMENT ON COLUMN "TRN_TRFD"."CAT" IS 'CAT能力';
   COMMENT ON COLUMN "TRN_TRFD"."RFLTYPE" IS '高度类型';
   COMMENT ON COLUMN "TRN_TRFD"."RFL" IS '巡航高度';
   COMMENT ON COLUMN "TRN_TRFD"."UPDATETIME" IS '更新时间';


   --添加主键
   ALTER TABLE TRN_AERD_APTC ADD PRIMARY KEY(UUID);
   ALTER TABLE TRN_AERD_TMRO ADD PRIMARY KEY(UUID);
   ALTER TABLE TRN_AFP ADD PRIMARY KEY(FTMID);
   ALTER TABLE TRN_FTMI ADD PRIMARY KEY(FTMID);
   ALTER TABLE TRN_MIT ADD PRIMARY KEY(FTMID);
   ALTER TABLE TRN_GDP ADD PRIMARY KEY(FTMID);
   ALTER TABLE TRN_GS ADD PRIMARY KEY(FTMID);
   ALTER TABLE TRN_AGMT_AGREEMENT ADD PRIMARY KEY(AGMTID);
   ALTER TABLE TRN_MDRS ADD PRIMARY KEY(MDRSID);
   ALTER TABLE TRN_MDRS_DETAIL ADD PRIMARY KEY(ID);
   ALTER TABLE TRN_NFPD ADD PRIMARY KEY(GUID);